baseURL: 'https://notes.evaron.ru/'
languageCode: 'en-us'
title: 'Notes by Peter Galonza'
theme: 'hugo-geekdoc'

pygmentsUseClasses: true
pygmentsCodeFences: true
disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  tag: tags

params:
  geekdocCollapseAllSections: true
  geekdocRepo: "https://github.com/pgalonza/Notes"
  geekdocContentLicense:
    name: Apache-2.0 license
    link: https://github.com/pgalonza/Notes/blob/master/LICENSE