---
- hosts: all
  become: true
  tasks:
    - name: Create a ansible user
      user:
        name: <user_name>
        append: true
        password: <user_password>
        groups: wheel
        group: administrator
        shell: /bin/bash
        state: present
        system: no
        create_home: true
        home: /home/
    - name: Set authorized key taken from file
      authorized_key:
        user: <user_name>
        state: present
        key: "{{ lookup('file', '/home/user/.ssh/id_rsa.pub') }}"
