# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.box = "<box_name>"
    config.vm.synced_folder "<src_path>", "<dst_path>", create: true
    config.vm.define "<name>#{i}" do |node| 
      node.vm.hostname = "<host_name>#{i}"
      # configure network ports
      node.vm.network "forwarded_port", host: "<port_number>#{i}", guest: <port_number>
      node.vm.network "private_network", ip: "<local_ip>#{i}",
          name: "vboxnet0"
      node.vm.network "public_network", type: "dhcp",
          name: "eno1"

      node.vm.provider "virtualbox" do |vb|
          vb.cpus = 1
          vb.memory = 4096
          vb.gui = false
          vb.name = "<vm_name>#{i}"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf install epel-release -y
  SHEL
end

Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/9"
  config.vm.synced_folder "<host folder>", "<guest folder>"
  config.vm.define "vrrp1" do |vrrp1|
    vrrp1.vm.hostname = "<host name>"
    vrrp1.vm.network "private_network", ip: "<host ip>",
      name: "vboxnet0"
    vrrp1.vm.provider "virtualbox" do |vb1|
      vb1.name = "VRRP1"
    end
  end

  config.vm.define "vrrp2" do |vrrp2|
    vrrp2.vm.hostname = "<host name>"
    vrrp2.vm.network "private_network", ip: "<host ip>",
      name: "vboxnet0"
    vrrp2.vm.provider "virtualbox" do |vb2|
      vb2.name = "VRRP2"
    end
  end

  config.vm.network "public_network", type: "dhcp",
    name: "eno1"

  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 4096
      vb.gui = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf install kernel-devel -y
    dnf install libXt -y
    dnf install libXext -y
    dnf install libX11 -y
    dnf install libXmu -y
    dnf install epel-release -y
    dnf install vim -y
  SHELL
end
